/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthAuth
 */
export interface AuthAuth {
    /**
     * token
     * @type {string}
     * @memberof AuthAuth
     */
    'token_type'?: string;
    /**
     * 过期时间（秒）
     * @type {number}
     * @memberof AuthAuth
     */
    'expires_in'?: number;
    /**
     * 密钥
     * @type {string}
     * @memberof AuthAuth
     */
    'access_token'?: string;
}

