/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CourseSimpleCourse1 } from './course-simple-course1';

/**
 * 
 * @export
 * @interface CourseStudentCourseBill
 */
export interface CourseStudentCourseBill {
    /**
     * ID
     * @type {number}
     * @memberof CourseStudentCourseBill
     */
    'id'?: number;
    /**
     * 支付状态
     * @type {number}
     * @memberof CourseStudentCourseBill
     */
    'pay_status'?: number;
    /**
     * 支付状态名称
     * @type {string}
     * @memberof CourseStudentCourseBill
     */
    'pay_status_name'?: string;
    /**
     * 账单费用
     * @type {number}
     * @memberof CourseStudentCourseBill
     */
    'bill_fees'?: number;
    /**
     * 支付时间
     * @type {string}
     * @memberof CourseStudentCourseBill
     */
    'pay_time'?: string | null;
    /**
     * 支付金额
     * @type {number}
     * @memberof CourseStudentCourseBill
     */
    'paid_fees'?: number;
    /**
     * 
     * @type {CourseSimpleCourse1}
     * @memberof CourseStudentCourseBill
     */
    'course'?: CourseSimpleCourse1;
}

