/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CourseSimpleCourse } from './course-simple-course';

/**
 *
 * @export
 * @interface CourseCourse
 */
export interface CourseCourse {
    student_ids: any[];
    fees: any;
    date: string;
    content: string;
    name: string;
    /**
     * ID
     * @type {number}
     * @memberof CourseCourse
     */
    'id'?: number;
    /**
     *
     * @type {CourseSimpleCourse}
     * @memberof CourseCourse
     */
    'course'?: CourseSimpleCourse;
}

