/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CourseSimpleCourse1
 */
export interface CourseSimpleCourse1 {
    /**
     * ID
     * @type {number}
     * @memberof CourseSimpleCourse1
     */
    'id'?: number;
    /**
     * 课程名称
     * @type {string}
     * @memberof CourseSimpleCourse1
     */
    'name'?: string;
}

