/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CourseSimpleCourse
 */
export interface CourseSimpleCourse {
    /**
     * 课程名称
     * @type {string}
     * @memberof CourseSimpleCourse
     */
    'name'?: string;
    /**
     * 课程时间
     * @type {string}
     * @memberof CourseSimpleCourse
     */
    'date'?: string | null;
    /**
     * 课程内容
     * @type {string}
     * @memberof CourseSimpleCourse
     */
    'content'?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof CourseSimpleCourse
     */
    'create_time'?: string;
}

