/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CourseCourse1
 */
export interface CourseCourse1 {
    /**
     * ID
     * @type {number}
     * @memberof CourseCourse1
     */
    'id'?: number;
    /**
     * 课程名称
     * @type {string}
     * @memberof CourseCourse1
     */
    'name'?: string;
    /**
     * 课程时间
     * @type {string}
     * @memberof CourseCourse1
     */
    'date'?: string;
    /**
     * 课程费用
     * @type {number}
     * @memberof CourseCourse1
     */
    'fees'?: number;
    /**
     * 课程内容
     * @type {string}
     * @memberof CourseCourse1
     */
    'content'?: string | null;
    /**
     * 学生ID
     * @type {Array<number>}
     * @memberof CourseCourse1
     */
    'student_ids'?: Array<number>;
    /**
     * 
     * @type {Array<object>}
     * @memberof CourseCourse1
     */
    'students'?: Array<object>;
    /**
     * 创建时间
     * @type {string}
     * @memberof CourseCourse1
     */
    'create_time'?: string;
}

