/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 学生课程账单集合
 * @export
 * @interface PatchTeacherApiCourseRequestStudentCourseBillsInner
 */
export interface PatchTeacherApiCourseRequestStudentCourseBillsInner {
    /**
     * 学生课程账单ID
     * @type {number}
     * @memberof PatchTeacherApiCourseRequestStudentCourseBillsInner
     */
    'id'?: number | null;
    /**
     * 学生课程账单学生ID
     * @type {number}
     * @memberof PatchTeacherApiCourseRequestStudentCourseBillsInner
     */
    'student_id'?: number;
}

