/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchTeacherApiCourseBillRequest
 */
export interface PatchTeacherApiCourseBillRequest {
    /**
     * 课程IDs
     * @type {Array<number>}
     * @memberof PatchTeacherApiCourseBillRequest
     */
    'course_ids': Array<number>;
}

