/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchTeacherApiCourseRequest
 */
export interface PatchTeacherApiCourseRequest {
    /**
     * 课程名称
     * @type {string}
     * @memberof PatchTeacherApiCourseRequest
     */
    'name': string;
    /**
     * 课程内容
     * @type {string}
     * @memberof PatchTeacherApiCourseRequest
     */
    'content': string;
    /**
     * 上课时间
     * @type {string}
     * @memberof PatchTeacherApiCourseRequest
     */
    'date': string;
    /**
     * 课程费用
     * @type {number}
     * @memberof PatchTeacherApiCourseRequest
     */
    'fees': number;
    /**
     * 学生IDs
     * @type {Array<number>}
     * @memberof PatchTeacherApiCourseRequest
     */
    'student_ids': Array<number>;
}

