/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostApiCommonApiLoginRequest
 */
export interface PostApiCommonApiLoginRequest {
    /**
     * 用户
     * @type {string}
     * @memberof PostApiCommonApiLoginRequest
     */
    'username': string;
    /**
     * 密码
     * @type {string}
     * @memberof PostApiCommonApiLoginRequest
     */
    'password': string;
    /**
     * 登录平台
     * @type {number}
     * @memberof PostApiCommonApiLoginRequest
     */
    'guard_type': number;
}

