/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUserCard2
 */
export interface UserUserCard2 {
    /**
     * 卡id
     * @type {number}
     * @memberof UserUserCard2
     */
    'id'?: number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof UserUserCard2
     */
    'brand_name'?: string;
    /**
     * 卡号
     * @type {string}
     * @memberof UserUserCard2
     */
    'number'?: string;
    /**
     * 过期时间
     * @type {string}
     * @memberof UserUserCard2
     */
    'expiration_date'?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof UserUserCard2
     */
    'create_time'?: string;
}

