/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserUserCard2 } from './user-user-card2';

/**
 * 
 * @export
 * @interface UserUser1
 */
export interface UserUser1 {
    /**
     * 用戶id
     * @type {number}
     * @memberof UserUser1
     */
    'id'?: number;
    /**
     * 用户姓名
     * @type {string}
     * @memberof UserUser1
     */
    'name'?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof UserUser1
     */
    'create_time'?: string | null;
    /**
     * 
     * @type {Array<UserUserCard2>}
     * @memberof UserUser1
     */
    'cards'?: Array<UserUserCard2>;
}

