/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUserNode
 */
export interface UserUserNode {
    /**
     * 地址
     * @type {string}
     * @memberof UserUserNode
     */
    'uri'?: string;
    /**
     * 节点标志
     * @type {string}
     * @memberof UserUserNode
     */
    'sign'?: string;
}

