/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { BasicCourse } from '../model';
// @ts-ignore
import { BasicStudent } from '../model';
/**
 * BasicSimpleApi - axios parameter creator
 * @export
 */
export const BasicSimpleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 课程列表
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiCommonApiCourses: async (authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/common-api/courses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 学生列表
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiCommonApiStudents: async (authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/common-api/students`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BasicSimpleApi - functional programming interface
 * @export
 */
export const BasicSimpleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BasicSimpleApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 课程列表
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApiCommonApiCourses(authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BasicCourse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApiCommonApiCourses(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BasicSimpleApi.getApiCommonApiCourses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 学生列表
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApiCommonApiStudents(authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BasicStudent>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApiCommonApiStudents(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BasicSimpleApi.getApiCommonApiStudents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BasicSimpleApi - factory interface
 * @export
 */
export const BasicSimpleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BasicSimpleApiFp(configuration)
    return {
        /**
         * 
         * @summary 课程列表
         * @param {BasicSimpleApiGetApiCommonApiCoursesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiCommonApiCourses(requestParameters: BasicSimpleApiGetApiCommonApiCoursesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<BasicCourse>> {
            return localVarFp.getApiCommonApiCourses(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 学生列表
         * @param {BasicSimpleApiGetApiCommonApiStudentsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApiCommonApiStudents(requestParameters: BasicSimpleApiGetApiCommonApiStudentsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<BasicStudent>> {
            return localVarFp.getApiCommonApiStudents(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getApiCommonApiCourses operation in BasicSimpleApi.
 * @export
 * @interface BasicSimpleApiGetApiCommonApiCoursesRequest
 */
export interface BasicSimpleApiGetApiCommonApiCoursesRequest {
    /**
     * 授权
     * @type {string}
     * @memberof BasicSimpleApiGetApiCommonApiCourses
     */
    readonly authorization?: string
}

/**
 * Request parameters for getApiCommonApiStudents operation in BasicSimpleApi.
 * @export
 * @interface BasicSimpleApiGetApiCommonApiStudentsRequest
 */
export interface BasicSimpleApiGetApiCommonApiStudentsRequest {
    /**
     * 授权
     * @type {string}
     * @memberof BasicSimpleApiGetApiCommonApiStudents
     */
    readonly authorization?: string
}

/**
 * BasicSimpleApi - object-oriented interface
 * @export
 * @class BasicSimpleApi
 * @extends {BaseAPI}
 */
export class BasicSimpleApi extends BaseAPI {
    /**
     * 
     * @summary 课程列表
     * @param {BasicSimpleApiGetApiCommonApiCoursesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BasicSimpleApi
     */
    public getApiCommonApiCourses(requestParameters: BasicSimpleApiGetApiCommonApiCoursesRequest = {}, options?: RawAxiosRequestConfig) {
        return BasicSimpleApiFp(this.configuration).getApiCommonApiCourses(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 学生列表
     * @param {BasicSimpleApiGetApiCommonApiStudentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BasicSimpleApi
     */
    public getApiCommonApiStudents(requestParameters: BasicSimpleApiGetApiCommonApiStudentsRequest = {}, options?: RawAxiosRequestConfig) {
        return BasicSimpleApiFp(this.configuration).getApiCommonApiStudents(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

