/* tslint:disable */
/* eslint-disable */
/**
 * 学校
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { CourseCourse } from '../model';
// @ts-ignore
import { CourseCourse1 } from '../model';
// @ts-ignore
import { CourseCourseBill } from '../model';
// @ts-ignore
import { PatchStudentApiCourseBillPayRequest } from '../model';
// @ts-ignore
import { PatchTeacherApiCourseRequest } from '../model';
/**
 * CourseCourseApi - axios parameter creator
 * @export
 */
export const CourseCourseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 课程-课程管理-课程删除
         * @param {number} courseId 
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTeacherApiCourse: async (courseId: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('deleteTeacherApiCourse', 'courseId', courseId)
            const localVarPath = `/teacher-api/courses/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 账单-账单管理-账单列表
         * @param {number} [page] 页数，默认1
         * @param {number} [perPage] 每页条数，默认15，最大200
         * @param {number} [payStatus] 账单状态
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentApiCourseBills: async (page?: number, perPage?: number, payStatus?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/student-api/course-bills`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (payStatus !== undefined) {
                localVarQueryParameter['pay_status'] = payStatus;
            }

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 课程-课程管理-课程列表
         * @param {number} [page] 页数，默认1
         * @param {number} [perPage] 每页条数，默认15，最大200
         * @param {string} [courseName] 课程名称
         * @param {string} [courseDate] 上课日期
         * @param {number} [billFees] 账单费用
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentApiCourses: async (page?: number, perPage?: number, courseName?: string, courseDate?: string, billFees?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/student-api/courses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (courseName !== undefined) {
                localVarQueryParameter['course_name'] = courseName;
            }

            if (courseDate !== undefined) {
                localVarQueryParameter['course_date'] = courseDate;
            }

            if (billFees !== undefined) {
                localVarQueryParameter['bill_fees'] = billFees;
            }

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 课程-课程管理-课程详情
         * @param {number} courseId 
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeacherApiCourse: async (courseId: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('getTeacherApiCourse', 'courseId', courseId)
            const localVarPath = `/teacher-api/courses/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 课程-课程管理-课程列表
         * @param {number} [page] 页数，默认1
         * @param {number} [perPage] 每页条数，默认15，最大200
         * @param {string} [name] 课程名称
         * @param {string} [date] 上课日期
         * @param {number} [fees] 课程费用
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeacherApiCourses: async (page?: number, perPage?: number, name?: string, date?: string, fees?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/teacher-api/courses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (date !== undefined) {
                localVarQueryParameter['date'] = date;
            }

            if (fees !== undefined) {
                localVarQueryParameter['fees'] = fees;
            }

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 账单-账单管理-账单支付
         * @param {string} courseBillId 
         * @param {string} [authorization] 授权
         * @param {PatchStudentApiCourseBillPayRequest} [patchStudentApiCourseBillPayRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchStudentApiCourseBillPay: async (courseBillId: string, authorization?: string, patchStudentApiCourseBillPayRequest?: PatchStudentApiCourseBillPayRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseBillId' is not null or undefined
            assertParamExists('patchStudentApiCourseBillPay', 'courseBillId', courseBillId)
            const localVarPath = `/student-api/course-bills/{courseBillId}/pay`
                .replace(`{${"courseBillId"}}`, encodeURIComponent(String(courseBillId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchStudentApiCourseBillPayRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 课程-课程管理-课程更新
         * @param {string} courseId 
         * @param {string} [authorization] 授权
         * @param {PatchTeacherApiCourseRequest} [patchTeacherApiCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchTeacherApiCourse: async (courseId: string, authorization?: string, patchTeacherApiCourseRequest?: PatchTeacherApiCourseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('patchTeacherApiCourse', 'courseId', courseId)
            const localVarPath = `/teacher-api/courses/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchTeacherApiCourseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 课程-课程管理-课程添加
         * @param {string} [authorization] 授权
         * @param {PatchTeacherApiCourseRequest} [patchTeacherApiCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTeacherApiCourses: async (authorization?: string, patchTeacherApiCourseRequest?: PatchTeacherApiCourseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/teacher-api/courses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchTeacherApiCourseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CourseCourseApi - functional programming interface
 * @export
 */
export const CourseCourseApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CourseCourseApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 课程-课程管理-课程删除
         * @param {number} courseId 
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTeacherApiCourse(courseId: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTeacherApiCourse(courseId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseCourseApi.deleteTeacherApiCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 账单-账单管理-账单列表
         * @param {number} [page] 页数，默认1
         * @param {number} [perPage] 每页条数，默认15，最大200
         * @param {number} [payStatus] 账单状态
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStudentApiCourseBills(page?: number, perPage?: number, payStatus?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CourseCourseBill>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStudentApiCourseBills(page, perPage, payStatus, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseCourseApi.getStudentApiCourseBills']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 课程-课程管理-课程列表
         * @param {number} [page] 页数，默认1
         * @param {number} [perPage] 每页条数，默认15，最大200
         * @param {string} [courseName] 课程名称
         * @param {string} [courseDate] 上课日期
         * @param {number} [billFees] 账单费用
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStudentApiCourses(page?: number, perPage?: number, courseName?: string, courseDate?: string, billFees?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CourseCourse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStudentApiCourses(page, perPage, courseName, courseDate, billFees, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseCourseApi.getStudentApiCourses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 课程-课程管理-课程详情
         * @param {number} courseId 
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTeacherApiCourse(courseId: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseCourse1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTeacherApiCourse(courseId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseCourseApi.getTeacherApiCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 课程-课程管理-课程列表
         * @param {number} [page] 页数，默认1
         * @param {number} [perPage] 每页条数，默认15，最大200
         * @param {string} [name] 课程名称
         * @param {string} [date] 上课日期
         * @param {number} [fees] 课程费用
         * @param {string} [authorization] 授权
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTeacherApiCourses(page?: number, perPage?: number, name?: string, date?: string, fees?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CourseCourse1>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTeacherApiCourses(page, perPage, name, date, fees, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseCourseApi.getTeacherApiCourses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 账单-账单管理-账单支付
         * @param {string} courseBillId 
         * @param {string} [authorization] 授权
         * @param {PatchStudentApiCourseBillPayRequest} [patchStudentApiCourseBillPayRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchStudentApiCourseBillPay(courseBillId: string, authorization?: string, patchStudentApiCourseBillPayRequest?: PatchStudentApiCourseBillPayRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchStudentApiCourseBillPay(courseBillId, authorization, patchStudentApiCourseBillPayRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseCourseApi.patchStudentApiCourseBillPay']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 课程-课程管理-课程更新
         * @param {string} courseId 
         * @param {string} [authorization] 授权
         * @param {PatchTeacherApiCourseRequest} [patchTeacherApiCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchTeacherApiCourse(courseId: string, authorization?: string, patchTeacherApiCourseRequest?: PatchTeacherApiCourseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseCourse1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchTeacherApiCourse(courseId, authorization, patchTeacherApiCourseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseCourseApi.patchTeacherApiCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 课程-课程管理-课程添加
         * @param {string} [authorization] 授权
         * @param {PatchTeacherApiCourseRequest} [patchTeacherApiCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postTeacherApiCourses(authorization?: string, patchTeacherApiCourseRequest?: PatchTeacherApiCourseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseCourse1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postTeacherApiCourses(authorization, patchTeacherApiCourseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseCourseApi.postTeacherApiCourses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CourseCourseApi - factory interface
 * @export
 */
export const CourseCourseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CourseCourseApiFp(configuration)
    return {
        /**
         * 
         * @summary 课程-课程管理-课程删除
         * @param {CourseCourseApiDeleteTeacherApiCourseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTeacherApiCourse(requestParameters: CourseCourseApiDeleteTeacherApiCourseRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deleteTeacherApiCourse(requestParameters.courseId, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 账单-账单管理-账单列表
         * @param {CourseCourseApiGetStudentApiCourseBillsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentApiCourseBills(requestParameters: CourseCourseApiGetStudentApiCourseBillsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseCourseBill>> {
            return localVarFp.getStudentApiCourseBills(requestParameters.page, requestParameters.perPage, requestParameters.payStatus, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 课程-课程管理-课程列表
         * @param {CourseCourseApiGetStudentApiCoursesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudentApiCourses(requestParameters: CourseCourseApiGetStudentApiCoursesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseCourse>> {
            return localVarFp.getStudentApiCourses(requestParameters.page, requestParameters.perPage, requestParameters.courseName, requestParameters.courseDate, requestParameters.billFees, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 课程-课程管理-课程详情
         * @param {CourseCourseApiGetTeacherApiCourseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeacherApiCourse(requestParameters: CourseCourseApiGetTeacherApiCourseRequest, options?: RawAxiosRequestConfig): AxiosPromise<CourseCourse1> {
            return localVarFp.getTeacherApiCourse(requestParameters.courseId, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 课程-课程管理-课程列表
         * @param {CourseCourseApiGetTeacherApiCoursesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTeacherApiCourses(requestParameters: CourseCourseApiGetTeacherApiCoursesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseCourse1>> {
            return localVarFp.getTeacherApiCourses(requestParameters.page, requestParameters.perPage, requestParameters.name, requestParameters.date, requestParameters.fees, requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 账单-账单管理-账单支付
         * @param {CourseCourseApiPatchStudentApiCourseBillPayRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchStudentApiCourseBillPay(requestParameters: CourseCourseApiPatchStudentApiCourseBillPayRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.patchStudentApiCourseBillPay(requestParameters.courseBillId, requestParameters.authorization, requestParameters.patchStudentApiCourseBillPayRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 课程-课程管理-课程更新
         * @param {CourseCourseApiPatchTeacherApiCourseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchTeacherApiCourse(requestParameters: CourseCourseApiPatchTeacherApiCourseRequest, options?: RawAxiosRequestConfig): AxiosPromise<CourseCourse1> {
            return localVarFp.patchTeacherApiCourse(requestParameters.courseId, requestParameters.authorization, requestParameters.patchTeacherApiCourseRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 课程-课程管理-课程添加
         * @param {CourseCourseApiPostTeacherApiCoursesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTeacherApiCourses(requestParameters: CourseCourseApiPostTeacherApiCoursesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CourseCourse1> {
            return localVarFp.postTeacherApiCourses(requestParameters.authorization, requestParameters.patchTeacherApiCourseRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteTeacherApiCourse operation in CourseCourseApi.
 * @export
 * @interface CourseCourseApiDeleteTeacherApiCourseRequest
 */
export interface CourseCourseApiDeleteTeacherApiCourseRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseCourseApiDeleteTeacherApiCourse
     */
    readonly courseId: number

    /**
     * 授权
     * @type {string}
     * @memberof CourseCourseApiDeleteTeacherApiCourse
     */
    readonly authorization?: string
}

/**
 * Request parameters for getStudentApiCourseBills operation in CourseCourseApi.
 * @export
 * @interface CourseCourseApiGetStudentApiCourseBillsRequest
 */
export interface CourseCourseApiGetStudentApiCourseBillsRequest {
    /**
     * 页数，默认1
     * @type {number}
     * @memberof CourseCourseApiGetStudentApiCourseBills
     */
    readonly page?: number

    /**
     * 每页条数，默认15，最大200
     * @type {number}
     * @memberof CourseCourseApiGetStudentApiCourseBills
     */
    readonly perPage?: number

    /**
     * 账单状态
     * @type {number}
     * @memberof CourseCourseApiGetStudentApiCourseBills
     */
    readonly payStatus?: number

    /**
     * 授权
     * @type {string}
     * @memberof CourseCourseApiGetStudentApiCourseBills
     */
    readonly authorization?: string
}

/**
 * Request parameters for getStudentApiCourses operation in CourseCourseApi.
 * @export
 * @interface CourseCourseApiGetStudentApiCoursesRequest
 */
export interface CourseCourseApiGetStudentApiCoursesRequest {
    /**
     * 页数，默认1
     * @type {number}
     * @memberof CourseCourseApiGetStudentApiCourses
     */
    readonly page?: number

    /**
     * 每页条数，默认15，最大200
     * @type {number}
     * @memberof CourseCourseApiGetStudentApiCourses
     */
    readonly perPage?: number

    /**
     * 课程名称
     * @type {string}
     * @memberof CourseCourseApiGetStudentApiCourses
     */
    readonly courseName?: string

    /**
     * 上课日期
     * @type {string}
     * @memberof CourseCourseApiGetStudentApiCourses
     */
    readonly courseDate?: string

    /**
     * 账单费用
     * @type {number}
     * @memberof CourseCourseApiGetStudentApiCourses
     */
    readonly billFees?: number

    /**
     * 授权
     * @type {string}
     * @memberof CourseCourseApiGetStudentApiCourses
     */
    readonly authorization?: string
}

/**
 * Request parameters for getTeacherApiCourse operation in CourseCourseApi.
 * @export
 * @interface CourseCourseApiGetTeacherApiCourseRequest
 */
export interface CourseCourseApiGetTeacherApiCourseRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseCourseApiGetTeacherApiCourse
     */
    readonly courseId: number

    /**
     * 授权
     * @type {string}
     * @memberof CourseCourseApiGetTeacherApiCourse
     */
    readonly authorization?: string
}

/**
 * Request parameters for getTeacherApiCourses operation in CourseCourseApi.
 * @export
 * @interface CourseCourseApiGetTeacherApiCoursesRequest
 */
export interface CourseCourseApiGetTeacherApiCoursesRequest {
    /**
     * 页数，默认1
     * @type {number}
     * @memberof CourseCourseApiGetTeacherApiCourses
     */
    readonly page?: number

    /**
     * 每页条数，默认15，最大200
     * @type {number}
     * @memberof CourseCourseApiGetTeacherApiCourses
     */
    readonly perPage?: number

    /**
     * 课程名称
     * @type {string}
     * @memberof CourseCourseApiGetTeacherApiCourses
     */
    readonly name?: string

    /**
     * 上课日期
     * @type {string}
     * @memberof CourseCourseApiGetTeacherApiCourses
     */
    readonly date?: string

    /**
     * 课程费用
     * @type {number}
     * @memberof CourseCourseApiGetTeacherApiCourses
     */
    readonly fees?: number

    /**
     * 授权
     * @type {string}
     * @memberof CourseCourseApiGetTeacherApiCourses
     */
    readonly authorization?: string
}

/**
 * Request parameters for patchStudentApiCourseBillPay operation in CourseCourseApi.
 * @export
 * @interface CourseCourseApiPatchStudentApiCourseBillPayRequest
 */
export interface CourseCourseApiPatchStudentApiCourseBillPayRequest {
    /**
     * 
     * @type {string}
     * @memberof CourseCourseApiPatchStudentApiCourseBillPay
     */
    readonly courseBillId: string

    /**
     * 授权
     * @type {string}
     * @memberof CourseCourseApiPatchStudentApiCourseBillPay
     */
    readonly authorization?: string

    /**
     * 
     * @type {PatchStudentApiCourseBillPayRequest}
     * @memberof CourseCourseApiPatchStudentApiCourseBillPay
     */
    readonly patchStudentApiCourseBillPayRequest?: PatchStudentApiCourseBillPayRequest
}

/**
 * Request parameters for patchTeacherApiCourse operation in CourseCourseApi.
 * @export
 * @interface CourseCourseApiPatchTeacherApiCourseRequest
 */
export interface CourseCourseApiPatchTeacherApiCourseRequest {
    /**
     * 
     * @type {string}
     * @memberof CourseCourseApiPatchTeacherApiCourse
     */
    readonly courseId: string

    /**
     * 授权
     * @type {string}
     * @memberof CourseCourseApiPatchTeacherApiCourse
     */
    readonly authorization?: string

    /**
     * 
     * @type {PatchTeacherApiCourseRequest}
     * @memberof CourseCourseApiPatchTeacherApiCourse
     */
    readonly patchTeacherApiCourseRequest?: PatchTeacherApiCourseRequest
}

/**
 * Request parameters for postTeacherApiCourses operation in CourseCourseApi.
 * @export
 * @interface CourseCourseApiPostTeacherApiCoursesRequest
 */
export interface CourseCourseApiPostTeacherApiCoursesRequest {
    /**
     * 授权
     * @type {string}
     * @memberof CourseCourseApiPostTeacherApiCourses
     */
    readonly authorization?: string

    /**
     * 
     * @type {PatchTeacherApiCourseRequest}
     * @memberof CourseCourseApiPostTeacherApiCourses
     */
    readonly patchTeacherApiCourseRequest?: PatchTeacherApiCourseRequest
}

/**
 * CourseCourseApi - object-oriented interface
 * @export
 * @class CourseCourseApi
 * @extends {BaseAPI}
 */
export class CourseCourseApi extends BaseAPI {
    /**
     * 
     * @summary 课程-课程管理-课程删除
     * @param {CourseCourseApiDeleteTeacherApiCourseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseCourseApi
     */
    public deleteTeacherApiCourse(requestParameters: CourseCourseApiDeleteTeacherApiCourseRequest, options?: RawAxiosRequestConfig) {
        return CourseCourseApiFp(this.configuration).deleteTeacherApiCourse(requestParameters.courseId, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 账单-账单管理-账单列表
     * @param {CourseCourseApiGetStudentApiCourseBillsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseCourseApi
     */
    public getStudentApiCourseBills(requestParameters: CourseCourseApiGetStudentApiCourseBillsRequest = {}, options?: RawAxiosRequestConfig) {
        return CourseCourseApiFp(this.configuration).getStudentApiCourseBills(requestParameters.page, requestParameters.perPage, requestParameters.payStatus, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 课程-课程管理-课程列表
     * @param {CourseCourseApiGetStudentApiCoursesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseCourseApi
     */
    public getStudentApiCourses(requestParameters: CourseCourseApiGetStudentApiCoursesRequest = {}, options?: RawAxiosRequestConfig) {
        return CourseCourseApiFp(this.configuration).getStudentApiCourses(requestParameters.page, requestParameters.perPage, requestParameters.courseName, requestParameters.courseDate, requestParameters.billFees, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 课程-课程管理-课程详情
     * @param {CourseCourseApiGetTeacherApiCourseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseCourseApi
     */
    public getTeacherApiCourse(requestParameters: CourseCourseApiGetTeacherApiCourseRequest, options?: RawAxiosRequestConfig) {
        return CourseCourseApiFp(this.configuration).getTeacherApiCourse(requestParameters.courseId, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 课程-课程管理-课程列表
     * @param {CourseCourseApiGetTeacherApiCoursesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseCourseApi
     */
    public getTeacherApiCourses(requestParameters: CourseCourseApiGetTeacherApiCoursesRequest = {}, options?: RawAxiosRequestConfig) {
        return CourseCourseApiFp(this.configuration).getTeacherApiCourses(requestParameters.page, requestParameters.perPage, requestParameters.name, requestParameters.date, requestParameters.fees, requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 账单-账单管理-账单支付
     * @param {CourseCourseApiPatchStudentApiCourseBillPayRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseCourseApi
     */
    public patchStudentApiCourseBillPay(requestParameters: CourseCourseApiPatchStudentApiCourseBillPayRequest, options?: RawAxiosRequestConfig) {
        return CourseCourseApiFp(this.configuration).patchStudentApiCourseBillPay(requestParameters.courseBillId, requestParameters.authorization, requestParameters.patchStudentApiCourseBillPayRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 课程-课程管理-课程更新
     * @param {CourseCourseApiPatchTeacherApiCourseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseCourseApi
     */
    public patchTeacherApiCourse(requestParameters: CourseCourseApiPatchTeacherApiCourseRequest, options?: RawAxiosRequestConfig) {
        return CourseCourseApiFp(this.configuration).patchTeacherApiCourse(requestParameters.courseId, requestParameters.authorization, requestParameters.patchTeacherApiCourseRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 课程-课程管理-课程添加
     * @param {CourseCourseApiPostTeacherApiCoursesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseCourseApi
     */
    public postTeacherApiCourses(requestParameters: CourseCourseApiPostTeacherApiCoursesRequest = {}, options?: RawAxiosRequestConfig) {
        return CourseCourseApiFp(this.configuration).postTeacherApiCourses(requestParameters.authorization, requestParameters.patchTeacherApiCourseRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

